// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquw_U0wFg-rNtF-6UZ5vFu7z2mO5BvhQ',
    appId: '1:149625306163:web:655ddc60e03ee7c24b3746',
    messagingSenderId: '149625306163',
    projectId: 'e-commerce-f194d',
    authDomain: 'e-commerce-f194d.firebaseapp.com',
    storageBucket: 'e-commerce-f194d.appspot.com',
    measurementId: 'G-WS30MRNNGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6an_RzMjXmCj21Rp9qzobs4sH-itevw',
    appId: '1:149625306163:android:c42fc8b48c1eeb994b3746',
    messagingSenderId: '149625306163',
    projectId: 'e-commerce-f194d',
    storageBucket: 'e-commerce-f194d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUYmgA4nPluVf6jACwkvN9UHaK9vNacE',
    appId: '1:149625306163:ios:703f6e94f9fe37334b3746',
    messagingSenderId: '149625306163',
    projectId: 'e-commerce-f194d',
    storageBucket: 'e-commerce-f194d.appspot.com',
    iosBundleId: 'com.example.flutterApplication18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNUYmgA4nPluVf6jACwkvN9UHaK9vNacE',
    appId: '1:149625306163:ios:703f6e94f9fe37334b3746',
    messagingSenderId: '149625306163',
    projectId: 'e-commerce-f194d',
    storageBucket: 'e-commerce-f194d.appspot.com',
    iosBundleId: 'com.example.flutterApplication18',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquw_U0wFg-rNtF-6UZ5vFu7z2mO5BvhQ',
    appId: '1:149625306163:web:425791c5491221594b3746',
    messagingSenderId: '149625306163',
    projectId: 'e-commerce-f194d',
    authDomain: 'e-commerce-f194d.firebaseapp.com',
    storageBucket: 'e-commerce-f194d.appspot.com',
    measurementId: 'G-94F39SW2DJ',
  );
}
